# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b237578b14d36e74d761b0ab57d3f2f444602f64e842a1a0c10dcb9dd89dac81299af04037a81f675e2b1245dfaf5ce944fa9ef7642e8f7498a1ca3c03f4f4e0

test:
  secret_key_base: b26f21bf0d26e3e63cb43428232a5783aac58f0451feb33eba05edff4be16b289b19976e4f4931378d845c3d92cfc4648f325d4887ef81884e8e60bda5e2bbe4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
